"""Add missing user fields

Revision ID: 1d444b22cbdd
Revises: 28a91d90f593
Create Date: 2026-09-19 15:03:39.313315+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d444b22cbdd'
down_revision: Union[str, None] = '28a91d90f593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('grad_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_institution_batch_name')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_batches_institution_id'), 'batches', ['institution_id'], unique=False)
    op.add_column('questions', sa.Column('database_schema', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('database_seed', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_batch_id'), 'users', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'users', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_batch_id'), table_name='users')
    op.drop_column('users', 'batch_id')
    op.drop_column('questions', 'database_seed')
    op.drop_column('questions', 'database_schema')
    op.drop_index(op.f('ix_batches_institution_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
