"""Candidate experience and labs

Revision ID: e1c437866509
Revises: 009_usage_budgets
Create Date: 2026-09-17 12:52:18.700290+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c437866509'
down_revision: Union[str, None] = '009_usage_budgets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_id'), 'labs', ['id'], unique=False)
    op.create_index(op.f('ix_labs_institution_id'), 'labs', ['institution_id'], unique=False)
    op.create_table('seats',
    sa.Column('lab_id', sa.Uuid(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_index(op.f('ix_seats_lab_id'), 'seats', ['lab_id'], unique=False)
    op.create_table('exam_seats',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_seats_candidate_id'), 'exam_seats', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_exam_seats_exam_id'), 'exam_seats', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_seats_id'), 'exam_seats', ['id'], unique=False)
    op.create_index(op.f('ix_exam_seats_seat_id'), 'exam_seats', ['seat_id'], unique=False)
    op.add_column('exam_responses', sa.Column('marks_awarded', sa.Float(), nullable=True))
    op.add_column('exam_responses', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.add_column('exam_responses', sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_sessions', sa.Column('total_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('exam_sessions', sa.Column('max_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('exam_sessions', sa.Column('percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('exam_sessions', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('exam_sessions', sa.Column('results_published', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('exam_sessions', sa.Column('client_ip', sa.String(length=255), nullable=True))
    op.add_column('exam_sessions', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('exam_sessions', sa.Column('user_agent', sa.String(length=1024), nullable=True))
    op.add_column('exam_sessions', sa.Column('browser', sa.String(length=255), nullable=True))
    op.add_column('exam_sessions', sa.Column('os_name', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('interview_sessions_exam_session_id_key'), 'interview_sessions', type_='unique')
    op.drop_index(op.f('ix_interview_sessions_exam_session_id'), table_name='interview_sessions')
    op.create_index(op.f('ix_interview_sessions_exam_session_id'), 'interview_sessions', ['exam_session_id'], unique=True)
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('batch_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('roll_no', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_users_roll_no'), 'users', ['roll_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_roll_no'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'roll_no')
    op.drop_column('users', 'batch_year')
    op.drop_column('users', 'section')
    op.drop_column('users', 'department')
    op.drop_index(op.f('ix_interview_sessions_exam_session_id'), table_name='interview_sessions')
    op.create_index(op.f('ix_interview_sessions_exam_session_id'), 'interview_sessions', ['exam_session_id'], unique=False)
    op.create_unique_constraint(op.f('interview_sessions_exam_session_id_key'), 'interview_sessions', ['exam_session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('exam_sessions', 'os_name')
    op.drop_column('exam_sessions', 'browser')
    op.drop_column('exam_sessions', 'user_agent')
    op.drop_column('exam_sessions', 'device_fingerprint')
    op.drop_column('exam_sessions', 'client_ip')
    op.drop_column('exam_sessions', 'results_published')
    op.drop_column('exam_sessions', 'rank')
    op.drop_column('exam_sessions', 'percentage')
    op.drop_column('exam_sessions', 'max_score')
    op.drop_column('exam_sessions', 'total_score')
    op.drop_column('exam_responses', 'graded_at')
    op.drop_column('exam_responses', 'is_correct')
    op.drop_column('exam_responses', 'marks_awarded')
    op.drop_index(op.f('ix_exam_seats_seat_id'), table_name='exam_seats')
    op.drop_index(op.f('ix_exam_seats_id'), table_name='exam_seats')
    op.drop_index(op.f('ix_exam_seats_exam_id'), table_name='exam_seats')
    op.drop_index(op.f('ix_exam_seats_candidate_id'), table_name='exam_seats')
    op.drop_table('exam_seats')
    op.drop_index(op.f('ix_seats_lab_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_labs_institution_id'), table_name='labs')
    op.drop_index(op.f('ix_labs_id'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
